In [2]:
import torch
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd 
import seaborn as sns
from pathlib import Path

In [3]:
perturbation_dir = Path("/Users/thomasbush/Downloads/perturbation_outputs/outputs")

In [4]:
p20_df = pd.read_csv(perturbation_dir / "p20" / "structure_scores.csv")
p40_df = pd.read_csv(perturbation_dir / "p40" / "structure_scores.csv")
p70_df = pd.read_csv(perturbation_dir / "p70" / "structure_scores.csv")

In [9]:
p20_df.sort_values(by="tm_score", ascending=True, inplace=True)
p20_df.head()

,sequence_idx,predicted_path,tm_score,rmsd
44,18553,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.878641,1.923988
29,12487,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.888574,2.161162
8,3208,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.889089,1.989658
7,3121,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.898117,2.046033
65,31815,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.898666,1.745639

In [ ]:
p40_df.sort_values(by="tm_score", ascending=True, inplace=True)
p40_df.head()

,sequence_idx,predicted_path,tm_score,rmsd
63,31367,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.505690,3.640473
25,11121,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.529575,4.585118
38,14784,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.577913,4.401949
41,16700,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.584310,4.599193
62,31282,/n/holylfs06/LABS/bsabatini_lab/Everyone/tbush...,0.594852,3.496942

: